### ISSUE TITLE
VGV naar pdf + mapbenaming

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#14]
1° beter toelichten waar vgv moet (naamgeving+locatie)
2° in studentrepo-voorbeeld voorbeeld tonen hoe je vgv mbv gitbook kunt generen
Cfr @Blarfursnarg : "Het is een eenvoudige oplossing en geeft een leesbare output,
het enige nadeel lijkt me dat de anchors in de summary niet lijken te werken (zoals beschreven hier: https://github.com/GitbookIO/gitbook/blob/master/docs/pages.md#anchors).
dit heeft als gevolg dat links niet gevolgd kunnen worden vanuit de table of contents en dat headers en footers in de PDF output niet kloppen.

Als deze oplossing gekozen zou worden kunnen misschien enkele zaken van de vgv1.md template naar README.md verplaatst worden, 
anders zal gitbook een lege pagina invoegen (aangezien README.md leeg is).
Titel, abstract en promotors kunnen bijvoorbeeld eventueel naar README.md.
"

**Comment by Blarfursnarg** [comment]
Relevante issue bij GitbookIO: https://github.com/GitbookIO/gitbook/issues/1200

**Comment by Blarfursnarg** [comment]
Gisteren kwam Gitbook 3.0.0 uit, waarin de hier besproken issue verholpen is. 
Na een `gitbook fetch latest` blijken de anchors etc. perfect te werken!

**Comment by timdams** [comment]
PDF generatie hoeft niet.

**Comment by luytsm** [comment]
PDF Generatie moet niet meer, hierdoor is een BAP StudentRepo  issue: https://github.com/AP-Elektronica-ICT/BAP_Stage_StudentRepo/issues/6
