### ISSUE TITLE
Gitbook editor

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#18]
Q:via commandline werkt dit, maar ik dacht eigenlijk dat we dit via 'gitbook editor' moesten doen. Of is dit niet het geval?
Heb die gitbook editor eens gebruikt (welliswaar buiten de repo want in de repo werkt deze 'nog' niet), deze editor werkt echt heel goed. automatisch genereren van table of content etc.

A:Neen hoor, de “gitbook editor” hoef je niet te gebruiken. Dit is een commercieel product dat ‘bovenop’ gitbook draait en vooral probeert inkomsten te genereren via selfpublishing boeken.

Bedoeling is dat je inderdaad de gewone commandline tool (of het .bat bestand dat ik in de repo heb gezet) en de nodige zaken zelf aanmaakt. Ik zal zeker eens bekijken of we de editor ook niet kunnen gebruiken, maar for now hoeft dat dus niet.

1° verduidelijken in stagesylalbus
2° bekijken of editor niet kan gebruikt worden

**Comment by timdams** [comment]
Zie ook https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/issues/29

**Comment by luytsm** [comment]
Je kan Gitbook.io ook gebruiken vanuit een bestaande repo, zoals ik nu heb gedaan met de stage syllabus. Dus je kan je favoriet text editor gebruik en de gitbook editor.

Ik ga dit sluiten omdat het een manier van werken is en afhankelijk is van de student.
