### ISSUE TITLE
Gitbook structuur in conflict met opbouw in scriptie.md

### ISSUE THREAD

**Issue by Blarfursnarg** [AP-Elektronica-ICT/BAP_Stage_Syllabus#21]
Gitbook maakt automatisch volgende structuur tijdens het genereren:

- Table of Contents ( = SUMMARY.md)
- 0.  Introduction ( = README.md, altijd hoofdstuk 0 met naam 'Introduction')
- x . xx  (verder gedefinieerde chapters en subchapters)
- ...
- x.  Glossary ( = GLOSSARY.md)

Dit is in conflict met de aangeraden opbouw in [scripte.md](https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/blob/master/StageSyllabus/Semester6/Deliverables/scriptie.md) :

- Inhoudsopgave
- Abstract
- Dankwoord
- Introductie (pas 3e hoofdstuk)
- ...

De volgorde van de gegenereerde hoofdstukken is niet aan te passen. Het is ook niet mogelijk README.md weg te laten, en indien leeg zal nog steeds een leeg hoofdstuk toegevoegd worden. 
Een mogelijke oplossing is het abstract in README.md schrijven, waardoor het vooraan verschijnt. Dit zal echter niets veranderen aan het feit dat de inhoudstafel het hoofdstuk nog steeds 'Introduction' zal noemen.

**Comment by timdams** [comment]
Good point. 
Ik pas het aan.

**Comment by timdams** [comment]
@Blarfursnarg  Klopt volgende volgorde? Indien ja, feel free to close issue :) https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/blob/master/StageSyllabus/Semester6/Deliverables/scriptie.md

**Comment by ErazerBrecht** [comment]
Introductie zou er nu twee keer staan.

Ene keer als abstract (De README.md van de scriptie)
En ene keer als introductie. 

Misschien die tweede naam aanpassen, om verwarring te vermijden

**Comment by MichaelMar93** [comment]
Het is perfect mogelijk om in de summary de README.md een andere naam te geven. Ik heb dit zo opgelost. Dan moet je enkel nog de titel in de README file veranderen naar abstract.

```
* [Abstract](README.md)
* [Dankwoord](book/dankwoord/dankwoord.md)
* [Introductie](book/introductie/introductie.md)
```

**Comment by timdams** [comment]
Great tips guys. Supermerci! Ik breng het straks in orde.
________________________________
Van: MichaelMar93<mailto:notifications@github.com>
Verzonden: ‎17/‎04/‎2016 18:19
Aan: AP-Elektronica-ICT/BAP_Stage_Syllabus<mailto:BAP_Stage_Syllabus@noreply.github.com>
CC: Tim Dams<mailto:dams.tim@telenet.be>
Onderwerp: Re: [AP-Elektronica-ICT/BAP_Stage_Syllabus] Gitbook structuur in conflict met opbouw in scriptie.md (#21)


Het is perfect mogelijk om in de summary de README.md een andere naam te geven. Ik heb dit zo opgelost. Dan moet je enkel nog de titel in de README file veranderen naar abstract.

* [Abstract](README.md)
* [Dankwoord](book/dankwoord/dankwoord.md)
* [Introductie](book/introductie/introductie.md)
