### ISSUE TITLE
Code in Markdown 

### ISSUE THREAD

**Issue by ErazerBrecht** [AP-Elektronica-ICT/BAP_Stage_Syllabus#23]
Markdown heeft de handige functie om code te schrijven:

```
Console.WriteLine("Hello World");
```

Echter geeft dit een 'probleem' bij omvormen naar PDF

![image](https://cloud.githubusercontent.com/assets/6287467/14582937/335130d8-0413-11e6-83e3-d83bf346c1f1.png)

Dit is letterlijk een printscreen van wat er in de pdf terecht komt indien de code te breed is.
Is dit erg? Of mag ik dit gewoon negeren? (Ik gok van niet but you never know)

**Comment by marcsmets7** [comment]
Dag Brecht,

 

Dit negeren lijkt mij nogal onhandig zeker als je code op verschillende plaatsen te breed is.

Een oplossing heb ik daarvoor ook niet zo onmiddellijk.

 

 

Mvg

 

 

 

Marc Smets

Lector 

Departement Wetenschap en Techniek, Campus Spoor Noord - Ellermanstraat, Ellermanstraat 33, BE-2060 Antwerpen

 marc.smets@ap.be <mailto:marc.smets@ap.be> 

 

Artesis Plantijn Hogeschool Antwerpen | www.ap.be <http://www.ap.be/> 



 

 

 

Van: Brecht Carlier [mailto:notifications@github.com] 
Verzonden: zaterdag 16 april 2016 20:42
Aan: AP-Elektronica-ICT/BAP_Stage_Syllabus <BAP_Stage_Syllabus@noreply.github.com>
Onderwerp: [AP-Elektronica-ICT/BAP_Stage_Syllabus] Code in Markdown (#23)

 

Markdown heeft de handige functie om code te schrijven:

Console.WriteLine("Hello World");

Echter geeft dit een 'probleem' bij omvormen naar PDF

 <https://cloud.githubusercontent.com/assets/6287467/14582937/335130d8-0413-11e6-83e3-d83bf346c1f1.png> 

Dit is letterlijk een printscreen van wat er in de pdf terecht komt indien de code te breed is.
Is dit erg? Of mag ik dit gewoon negeren? (Ik gok van niet but you never know)

**Comment by timdams** [comment]
Dag @ErazerBrecht ,

C# (en ook andere talen) ligt niet zo wakker van spaties en enters.
De makkelijkste optie is om je code die te lang is op te splitsen naar een volgende lijn.Oftewel doe je dit automatisch, anders (in Visual Studio) doe je dit zoals hier besproken.
http://stackoverflow.com/questions/236517/how-can-i-make-visual-studio-wrap-lines-at-80-characters

Sluit jij issue indien dit een aanvaardbare oplossing is aub, anders zoeken we verder.

**Comment by ErazerBrecht** [comment]
@timdams 
Ik ben het er opzich mee eens. Maar ik vind het persoonlijk jammer om code op een andere lijn te moeten zetten in markdown. Omdat ik de scrollbalk zo'n handige toevoeging vindt als je de code online bekijkt.

Dus de perfecte oplossing zou in mijn ogen zijn, scrollbalk bij het online bekijken en bij pdf enters.
Nu betwijfel ik of dat dit zou gaan.

Maar voor de voorlopige scriptie laat ik het zo staan, tegen de echte scriptie zullen we onze code versmallen dan.

Ik sluit deze issue nadat ik zelf nog eens gezocht heb. Waarschijnlijk komende week.

**Comment by timdams** [comment]
Please close this anders doe ik het!
