### ISSUE TITLE
gewenste manier voor referenties/bronvermeldingen?

### ISSUE THREAD

**Issue by Blarfursnarg** [AP-Elektronica-ICT/BAP_Stage_Syllabus#27]
Wat is de correcte manier om een uitspraak te bevestigen met een bron in de scriptie?

Enkele voorbeelden:
- Inline:  
  Mr. Doggen is [een beste kerel](https://about.me/jeroendoggen#!)
- References (zelfde end result als inline):  
  Mr. Doggen is [een beste kerel][jeroen]  
  [jeroen]: https://about.me/jeroendoggen#!
- [Gitbook Footnotes](http://toolchain.gitbook.com/syntax/markdown.html#footnotes):  
  Mr. Doggen is een beste kerel [^1]  
  [^1](Mr. Doggen's website)[https://about.me/jeroendoggen#!]
- Gewoon achteraan in de bronvermelding/bibliografie.

Inline en references zien er als gewone links uit in gitbook. De footnotes renderen als volgt:
![2016-04-22--1461321004_596x59_scrot](https://cloud.githubusercontent.com/assets/6714928/14739181/2bccbf90-0886-11e6-872f-d0832a4d0f81.png)
![2016-04-22--1461321023_358x55_scrot](https://cloud.githubusercontent.com/assets/6714928/14739182/2bce54f4-0886-11e6-96e1-446e60b6de83.png)

**Comment by timdams** [comment]
Ik vind de Gitbook footnote eigenlijk wel het properst. Iemand anders opinie?

Van: Oliver Hofkens [mailto:notifications@github.com]
Verzonden: vrijdag 22 april 2016 12:33
Aan: AP-Elektronica-ICT/BAP_Stage_Syllabus <BAP_Stage_Syllabus@noreply.github.com>
Onderwerp: [AP-Elektronica-ICT/BAP_Stage_Syllabus] gewenste manier voor referenties/bronvermeldingen? (#27)


Wat is de correcte manier om een uitspraak te bevestigen met een bron in de scriptie?

Enkele voorbeelden:

  *   Inline:
Mr. Doggen is een beste kerel<https://about.me/jeroendoggen#!>
  *   References (zelfde end result als inline):
Mr. Doggen is [een beste kerel][jeroen]
[jeroen]: https://about.me/jeroendoggen#<https://about.me/jeroendoggen>!
  *   Gitbook Footnotes<http://toolchain.gitbook.com/syntax/markdown.html#footnotes>:
Mr. Doggen is een beste kerel [^1]
^1<Mr.%20Doggen's%20website>[https://about.me/jeroendoggen#!]
  *   Gewoon achteraan in de bronvermelding/bibliografie.

Inline en references zien er als gewone links uit in gitbook. De footnotes renderen als volgt:
[2016-04-22--1461321004_596x59_scrot]<https://cloud.githubusercontent.com/assets/6714928/14739181/2bccbf90-0886-11e6-872f-d0832a4d0f81.png>
[2016-04-22--1461321023_358x55_scrot]<https://cloud.githubusercontent.com/assets/6714928/14739182/2bce54f4-0886-11e6-96e1-446e60b6de83.png>

**Comment by luytsm** [comment]
Toegevoegd in scriptie.md
b4ba8bddfea83c957dd264fcc5f1b097dd41f798
