### ISSUE TITLE
gitbook.io

### ISSUE THREAD

**Issue by luytsm** [AP-Elektronica-ICT/BAP_Stage_Syllabus#29]
https://jonascaers.gitbooks.io/network-voip-monitoring/content/

Leuk om te lezen, goede interface 
Op aandringen volgend jaar?

**Comment by timdams** [comment]
Duplicate issue, kga deze voorlopig sluiten. zie hier: https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/issues/18
