### ISSUE TITLE
Afspraken rond titels toevoegen

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#33]
Taal (Engels, Ned?)
Duidelijkheid, inhoud 
Geen slogan/reclame
Casing regels bij Engelse titels: http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html 
Geen punt op einde van zin

**Comment by luytsm** [comment]
# Scriptie Titel

De scriptie titel moet tegen de afgesproken datum worden ingeleverd. De titel
word in dezelfde taal als het eindwerk geschreven. Deze titel word ook niet
gebruikt om reclame te maken. Zorg ervoor dat de titel de inhoud reflecteert.
De titel van de BAP/Stage komt ook op je diploma.

Zie edc1507075d9cf8afc03b4edf75adc9bd62a4300
