### ISSUE TITLE
wireframes

### ISSUE THREAD

**Issue by luytsm** [AP-Elektronica-ICT/BAP_Stage_Syllabus#35]
Aanmoedigen van wireframes.

Sommige studenten moeten een frontend maken voor een applicatie, dit zijn meestal website. De student beschrijft deze paginas meestal textueel. Dit maakt het moeilijk om een beeld te vormen van de website. Als we wireframes aanmoedigen, dan zal de student een analyse op voorhand maken, wat het programmeerwerk vereenvoudigt en kan in de verslaggeving worden meegegeven

**Comment by timdams** [comment]
Done
672dfee4646e8b3b01991b63bfbcea41ac6357ba
