### ISSUE TITLE
Verduidelijking indienen deliverables

### ISSUE THREAD

**Issue by Blarfursnarg** [AP-Elektronica-ICT/BAP_Stage_Syllabus#36]
In timing.md staan volgende data:

* Indienen bachelorproefdeliverables (voorlaatste commit): 10 juni
* Eindpresentatie (laatste commit): 20-24 juni

Wilt dit zeggen dat op 10 juni alle deliverables binnen moeten (BAP, scriptie, video, scriptiesamenvatting), behalve de eindpresentatie?  Of horen de video en scriptiesamenvatting misschien eerder bij de eindpresentatie?

**Comment by timdams** [comment]
Alles moet op 10 juni binnen, exclusief de eindpresentatie. Dus in principe ook video en scriptiesamenvatting.
Maar ik sta open om dit te veranderen naar : BAP+scriptie binnen op 10 juni. Presentatie+samenvatting+video op 20 juni.

Wat denk je?

**Comment by Blarfursnarg** [comment]
Lijkt me wel aangenamer ja. Ik denk dat die 10 extra dagen voor velen (waaronder ikzelf) welkom zijn om aan die laatste zaken te werken!

Bedankt!

**Comment by ErazerBrecht** [comment]
Dat lijkt me nu een zeer strak plan!
Ik (wij) kunnen deze extra dagen ook wel gebruiken

**Comment by MichaelMar93** [comment]
Dit zou inderdaad veel aangenamer zijn.

**Comment by timdams** [comment]
19493a65147b34f0eab5bfc26b9b6470a541b80d

Indien duidelijk, gelieve issue te closen aub.

**Comment by Blarfursnarg** [comment]
Perfect, thanks!

**Comment by ErazerBrecht** [comment]
@timdams 
20 Juni it is? (Samenvatting, video en presentatie)

https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/blob/master/StageSyllabus/timing.md

Hier staat nog  20-24 Juni.
Ik betwijfel dat elke student deze issue zal bekijken.

**Comment by timdams** [comment]
De deadline is de dag van de eindpresentatie.
