### ISSUE TITLE
Riscoanalyse

### ISSUE THREAD

**Issue by ErazerBrecht** [AP-Elektronica-ICT/BAP_Stage_Syllabus#4]
Path: *StageSyllabus/Semester5/opstart.md*

> * het *Stagecontract/stageovereenkomst* opstellen en het stagereglement ondertekenen,
>  * **Optioneel**: Risicoanalyse en werkpostfiche,

Volgens dhr Smets is dit verplicht (Zie: Artikel 17, reglement). Niet duidelijk op te maken uit deze opsomming.
Misschien ineens verwijzen naar [Deze link](https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/blob/master/StageSyllabus/Semester5/opstart.md#risicoanalyse).

Dus kan ik stellen dat dit sowieso verplicht is bij alle bedrijven buiten éénmanszaken? Aka in denk ik bijna **geen** enkel geval optioneel...

NOOT de risico analyse is precies ook niet aanwezig voor éénmanszaken.

**Comment by timdams** [comment]
Optioneel weggehaald uit opsomming en belangrijkste zin bij toelichting vet gemaakt. Thx for the tip!
