### ISSUE TITLE
Scriptiesamenvatting weglaten?

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#42]

**Comment by ArneSchoonvliet** [comment]
Naar mijn mening Is het niet nuttig. Zover ik heb kunnen zien heeft nog
niemand van de gasten een samenvatting open gehad.
Op 22-jun.-2016 10:50 AM schreef "Tim Dams" <notifications@github.com>:

**Comment by luytsm** [comment]
Verwijderd in 54bdfb723c2f1ac48db83222df2421acd47573a8
