### ISSUE TITLE
Aantal dagen verhogen 

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#43]

**Comment by timdams** [comment]
BAP+Stage wordt 27 SP:

gevolg meer stagedagen
timing aanpassen
stagecontract en faq aanpassen

volgend jaar hebben derdejaars maar 2 weken examen in januari en 2 weken examen in juni.Concreet dus 15 lesweken. Hou daar rekening mee in planning bap volgend jaar.

**Comment by timdams** [comment]
Max 15 dagen 'verlof'

**Comment by timdams** [comment]
1 of 2 dagen nog voor Vak Luc Peeters

**Comment by timdams** [comment]
BAP dus amper combineerbaar met vakken uit andere semesters

**Comment by luytsm** [comment]
Aangepast in e22044bd2951ad9813cf558778a125f8e75e5dcd
Zie Stage Periode
