### ISSUE TITLE
elevatorpitch vervangen door abstract/readme.md v1

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#45]

**Comment by luytsm** [comment]
Elevator pitch al weghaald uit opstart sectie 
Commit: 9de20f53098b247f37f9d81ed5f14454b43df71a

**Comment by luytsm** [comment]
Dit zal worden gevraag in vgv1, waarvan de inleverdatum 3 weken na de start de stage is.

**Comment by luytsm** [comment]
Er wordt nu een grondige analyse van het onderwerp gevraagd in het eerste vgv
