### ISSUE TITLE
Opstart.md (Elevatorpitch)

### ISSUE THREAD

**Issue by ErazerBrecht** [AP-Elektronica-ICT/BAP_Stage_Syllabus#5]
[LINK](https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/blob/master/StageSyllabus/Semester5/opstart.md)
 

>Bedoeling is dat je tegen de examenperiode in januari een zogenaamde elevator pitch voorbereid. Deze pitch gebruik je om in enkele minuten je bahelorproefopdracht aan derden toe te lichten.Hiervoor dien je **2** zaken voor te bereiden: 1. Een presentatie van 2 slides

>1. (voorlopige) Titel + namen (jezelf, promotors, naam bedrijf)
2. Doel en beschrijving opdracht
  - Je pitch uitgeschreven in een tekst van minimum 350 en maximum 450 woorden
Deze dien je te presenteren in januari alsook digitaal in te dienen aan je promotors en stagecoordinator.

2 zaken?
Wat is het tweede buiten de presentatie, deze zin zorgt voor verwarring.

**Comment by timdams** [comment]
Ook je pitch uitschrijven naar 350/450 woordjes document dat mee in je repo komt (en je abstract zal worden)

Van: Brecht Carlier [mailto:notifications@github.com]
Verzonden: maandag 11 januari 2016 9:45
Aan: AP-Elektronica-ICT/BAP_Stage_Syllabus <BAP_Stage_Syllabus@noreply.github.com>
Onderwerp: [BAP_Stage_Syllabus] Opstart.md (Elevatorpitch) (#5)


LINK<https://github.com/AP-Elektronica-ICT/BAP_Stage_Syllabus/blob/master/StageSyllabus/Semester5/opstart.md>

Bedoeling is dat je tegen de examenperiode in januari een zogenaamde elevator pitch voorbereid. Deze pitch gebruik je om in enkele minuten je bahelorproefopdracht aan derden toe te lichten.Hiervoor dien je 2 zaken voor te bereiden: 1. Een presentatie van 2 slides

  1.  (voorlopige) Titel + namen (jezelf, promotors, naam bedrijf)
  2.  Doel en beschrijving opdracht

     *   Je pitch uitgeschreven in een tekst van minimum 350 en maximum 450 woorden Deze dien je te presenteren in januari alsook digitaal in te dienen aan je promotors en stagecoordinator.

2 zaken?
Wat is het tweede buiten de presentatie, deze zin zorgt voor verwarring.

**Comment by ErazerBrecht** [comment]
Thx
