### ISSUE TITLE
Scriptie glossary toevoegen

### ISSUE THREAD

**Issue by timdams** [AP-Elektronica-ICT/BAP_Stage_Syllabus#9]
Glossary

Allows you to specify terms and their respective definitions to be displayed in the glossary. Based on those terms, gitbook will automatically build an index and highlight those terms in pages.

The GLOSSARY.md format is very simple :

`# term`
Definition for this term

`# Another term`
With it's definition, this can contain bold text and all other kinds of inline markup ...

**Comment by luytsm** [comment]
Glossary staat al vermeld in de scriptie inhoud zie Deliverables > Scriptie (lijn28)
